export const REQUEST_START = "DISPATCH_REQUEST";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const PRODUCTADDED_SUCCESSFULLY = "PRODUCTADDED_SUCCESSFULLY";
export const PRODUCTADDED_FAIL = "PRODUCTADDED_FAIL";

export const PRODUCTLOADED_SUCCESSFULLY = "PRODUCTLOADED_SUCCESSFULLY";
export const PRODUCTLOADED_FAIL = "PRODUCTLOADED_FAIL";

